### ISSUE TITLE
Zookeeper namespace validation doesn't allow any namespace

### ISSUE THREAD

**Issue by lehphyro** [MeltwaterArchive/dropwizard-extra#25]
If I leave the namespace empty, curator says "/" isn't valid.
If I set namespace = test, a dropwizard-extra regexp validation says it isn't valid
If I set namespace = /test, curator says it isn't valid because it prepends a "/" itself to the namespace

**Comment by nicktelford** [comment]
Thanks for the bug report. Seems I didn't scrutise the Curator API quite hard enough. Please let me know if you discover any other issues.
