### ISSUE TITLE
Upgrade to Kafka 0.8

### ISSUE THREAD

**Issue by nicktelford** [MeltwaterArchive/dropwizard-extra#9]
Once Kafka 0.8 is released and a build is _finally_ available on Maven Central, we should upgrade to it.

This will require some modifications to the `KafkaConsumer` API, but should be worth it.

**Comment by novabyte** [comment]
@nicktelford Has there been any progress on this?

**Comment by nicktelford** [comment]
Not for the time being, I've been rather busy with other things. At any rate, I would want to re-write the Kafka consumer integration from scratch anyway, so you're probably better off doing your own thing.

**Comment by nicktelford** [comment]
This now exists in `master` in the main `dropwizard-extra-kafka` module.
